config/routes.rb
Scores::Application.routes.draw do
  get "histories/index"

  get "histories/create"

  get "histories/show"

  get "scores/new_calls"

  match "scores/create_calls", to: 'scores#create_calls'

  get "scores/new_wins"

  match "scores/create_wins", to: 'scores#create_wins'

  match "scores/undo", to: 'scores#undo'

  match "/res", to: 'users#re_session'

  match "/put", to: 'users#put_session'

  match "/admin", to: 'users#new'

  get "users/destroy_all"

  resources :users
  resources :histories, :only => [:index, :create, :show, :new]

  root :to => 'users#index'

end

app/models/history.rb
class History < ActiveRecord::Base
  attr_accessible :on, :end
  has_many :users
  has_many :scores, :through => :users 
end

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :num_calls, :num_wins, :record, :user_id, :set_call, :set_win, :history_id
  belongs_to :user
  belongs_to :history
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :name, :total, :history_id
  has_many :scores
  belongs_to :history

  validates :name, presence: true

  def get_total
  	self.scores.each do |s|
  		self.total += s.record
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def index
  	@histories = History.all
  end

  def new
    if History.last!=nil and History.last.end==true
    	session[:history] = 'on'
    	History.create(:on=>Date.today)
    end
  	redirect_to new_user_path
  end

  def create
  	History.create(:on=>Date.today)
  	redirect_to new_user_path
  end

  def show
  	@history = History.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def new_calls
  	@users = User.where("history_id = ?", session[:history_id])
  end

  def create_calls
  	#size = User.count
    users = User.where("history_id = ?", session[:history_id])
    users.each do |user|
      call_n = params["call"+(user.id).to_s].to_i
      s=user.scores.build(:num_calls => call_n,:set_call=>true,:set_win=>false,:history_id=>user.history_id)
      s.save
    end
    redirect_to users_path
  end

  def new_wins
  	@users = User.all
  end

  def create_wins
  	#size = User.count
    users = User.where("history_id = ?", session[:history_id])
    users.each do |user|
      win_n = params["win"+(user.id).to_s].to_i
      s=user.scores.last
      s.num_wins = win_n
      if s.num_calls == win_n
        s.record = 10+win_n**2
        user.total += (10+win_n**2)
      else
        s.record = -((s.num_calls-win_n).abs**2)
        user.total += -((s.num_calls-win_n).abs**2)
      end
      s.set_win = true
      user.save
      s.save
    end
    redirect_to users_path
  end

  def undo
    users = User.where("history_id = ?", session[:history_id])
    s_w = users.first.scores.last.set_win
    users.each do |user|
      s = user.scores.last
      if s_w
        s.set_win = false
        s.num_wins = nil
        user.total-=s.record
        s.record = nil
        s.save
        user.save
      else
        s.destroy
      end
    end
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include UsersHelper
  def index
    if History.last!=nil and History.last.end!=true
      @users = History.last.users
    else 
      @users = []
    end
  end

  def new
    if not start_recording?
      session[:history] = 'on'
      his = History.create(:on=>Date.today)
      session[:history_id] = his.id
    end
    @users = History.last.users
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.history_id = session[:history_id]
    @user.total = 0;
    @user.save

    if session[:remember_token]==nil
      session[:remember_token] = "check!"
    end

    if params[:commit]=="Next"
      redirect_to new_user_path
    else
      redirect_to users_path
    end

  end

  def destroy
  end

  def update
  end

  def destroy_all
    #User.destroy_all
    #Score.destroy_all
    h= History.last
    h.end = true
    h.save
    reset_session
    redirect_to '/'
  end

  def re_session
    reset_session
    redirect_to '/'
  end

  def put_session
    if session[:remember_token]==nil
      session[:remember_token] = "check!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
	def recent_call_num(id)
		u=User.find(id)
		if u.scores.last!=nil and u.scores.last.num_wins==nil
			return u.scores.last.num_calls
		end
		return "unknown"
	end
	def call_turn?
		(Score.last==nil) or (Score.last.set_call and Score.last.set_win)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		if session[:remember_token]!=nil
			User.find(session[:remember_token])
		end
	end

	def admin?
		if session[:remember_token]=="check!"
			return true
		end
		return false
	end

	def start_recording?
		if History.last!=nil
			return History.last.end==nil
		end
		return session['history']=='on'
	end

end

app/views/histories/create.html.erb
<h1>Histories#create</h1>
<p>Find me in app/views/histories/create.html.erb</p>

app/views/histories/index.html.erb
<%= link_to "Home", root_path%><br/>
<h1>Histories</h1>
<% for @his in @histories %>
	<%= link_to @his.on, history_path(@his)%>
<% end %>

app/views/histories/show.html.erb
<%= link_to "Home", root_path%> <%=link_to "History List", histories_path%><br/>
<h1><%= @history.on %></h1>
<%for @user in @history.users%>
<div id ="block">
	<table style="display: inline-block;"><tr><td id="name"><%= @user.name%></td></tr></table>
	<%for @score in @user.scores.order("created_at ASC")%>
		<table id="score" style="display: inline-block;">		
			<tr>
				<td id="call"><%= @score.num_calls%></td>
				<td id="win"><%= @score.num_wins%></td>
			</tr>
			<tr><td id="record"><%= @score.record%></td></tr>
		</table>
	<%end%>
	<table id="total" style="display: inline-block;">
		<tr>
			<td><%= @user.name%></td>
		</tr>
		<tr>
			<td><%= @user.total%></td>
		</tr>
	</table>
	<br/>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scores</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scores/create_calls.html.erb
<h1>Scores#create_calls</h1>
<p>Find me in app/views/scores/create_calls.html.erb</p>

app/views/scores/create_wins.html.erb
<h1>Scores#create_wins</h1>
<p>Find me in app/views/scores/create_wins.html.erb</p>

app/views/scores/new.html.erb
<%= form_tag controller: "scores", action: "new_calls", method: "post" do%>
	<%=@user.name%>
	<%= label_tag(:"call#{@user.id}","call") %>
	<%= text_field_tag(:"call#{@user.id}")%>
<% end %>

app/views/scores/new_calls.html.erb
<h1>Scores#new_calls</h1>
<%= form_tag controller: "scores", action: "create_calls", method: "post" do%>
	<% for @user in @users%>
		<%=@user.name%>
		<%= label_tag(:"call#{@user.id}","call") %>
		<%= text_field_tag :"call#{@user.id}" %>
		<br/>
	<% end %>
	<%= submit_tag("Commit Calls!") %>
<% end %>

app/views/scores/new_wins.html.erb
<h1>Scores#new_wins</h1>
<%= form_tag controller: "scores", action: "create_wins", method: "post" do%>
	<% for @user in @users%>
		<%=@user.name%>
		<%= label_tag(:"win#{@user.id}","win") %>
		<%= text_field_tag(:"win#{@user.id}")%>
		<br/>
	<% end %>
	<%= submit_tag("Commit Wins!") %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<body>
<%= link_to "Our GLORIOUS Histories", histories_path%><br/>
<div id="title" style="display: inline-block;"><%= link_to image_tag("dog.jpg", size: "500x300", alt: "Edit Entry"),url_for(params)%></div>
<%if @users==[]%>
<iframe width="560" height="315" src="//www.youtube.com/embed/ia8CKDIur3s" frameborder="0" allowfullscreen></iframe>
<%end%>
<div id="admin" style="display: inline-block;">
<% if admin? %>
<%= link_to "undo", scores_undo_path, {:id=>"undo",:confirm => 'Sure?'}%>
	<%if call_turn? %>
		<%= form_tag controller: "scores", action: "create_calls", method: "post" do%>
			<div id="input">
				<% for @user in @users%>
					<%=@user.name%>
					<%= label_tag(:"call#{@user.id}","call") %>
					<%= text_field_tag :"call#{@user.id}", nil,class: 'text_field' %>
					<br/>
				<% end %>
			</div>
			<div class = "button"><%= submit_tag("Commit Calls!") %></div>
		<% end %>
	<% else %>
		<%= form_tag controller: "scores", action: "create_wins", method: "post" do%>
			<div id="input">
				<% for @user in @users%>
					<%=@user.name%>
					<%= label_tag(:"win#{@user.id}","win") %>
					<%= text_field_tag(:"win#{@user.id}",nil ,class: 'text_field')%>
					<br/>
				<% end %>
			</div>
			<div class = "button"><%= submit_tag("Commit Wins!") %></div>
		<% end %>
	<% end %>
<% end %>
</div>


<!--div id="admin">
	<% if admin? %>
		Admin rights: <br/>
		<% if call_turn? %>
			<%= link_to "Enter calls", scores_new_calls_path, :id => "calls" %>
		<% else %>
			<%= link_to "Enter wins", scores_new_wins_path, :id => "wins"  %>
		<% end %>
		<%= link_to "undo", scores_undo_path, {:id=>"undo",:confirm => 'Sure?'}%>
	<%end%>
</div-->
<%if @users==[]%>
<iframe src="http://www.weweweb.net/game/webpage/gbridge-howto.html" width="100%" height="500">
  <p>Your browser does not support iframes.</p>
</iframe>
<% end %>
<%for @user in @users%>
<div id ="block">
	<table style="display: inline-block;"><tr><td id="name"><%= @user.name%></td></tr></table>
	<%for @score in @user.scores.order("created_at ASC")%>
		<table id="score" style="display: inline-block;">		
			<tr>
				<td id="call"><%= @score.num_calls%></td>
				<td id="win"><%= @score.num_wins%></td>
			</tr>
			<tr><td id="record"><%= @score.record%></td></tr>
		</table>
	<%end%>
	<table id="total" style="display: inline-block;">
		<tr>
			<td><%= @user.name%></td>
		</tr>
		<tr>
			<td><%= @user.total%></td>
		</tr>
	</table>
	<br/>
</div>
<%end%>
<% if admin? %>
	<%= link_to "Clear Data", 'users/destroy_all',{:confirm => 'Sure?'}%>
<%end%>
</body>
<br/>This Site Powered by <%=image_tag("rails.png") %>

app/views/users/new.html.erb
<h1>Sign up all player</h1>
<%=link_to "Home", '/'%><br/>
<%if @users %>
	<% for @u in @users %>
		<br/><%=@u.name%>
	<%end%>
<%end%>
<%= form_for(@user) do |f| %>
<div id="name_entry">
	<%= f.label :name %>
	<%= f.text_field :name,id:"name_box"%><br/>
	<div id="next_but">
		<%= f.submit "Next" %>
	</div>
	<%= f.submit "End" %>
</div>
<%end%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>